spring:
  application:
    name: backend
  mail:
    host: smtp.gmail.com
    port: 587
    username: serxan.babayev.06@gmail.com
    password: klmp yxwd jtdz ptmn
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
  datasource:
    first:
      url: jdbc:postgresql://localhost:5450/User
      username: root
      password: root
    second:
      url: jdbc:postgresql://localhost:5451/Product
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379
      # password: your-redis-password (əgər varsa)

cloudinary:
  cloud:
    name: dddwkgrcy
  api:
    key: 668583881613156
    secret: 7jymaVAgMxu5Pc50toz0YvwJ2ro